<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-JeremyKvale/blob/main/More_On_Numpy_Jeremy_Kvale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **More on NumPy**

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, vectorized numerical computations using arrays.

## **Review**
**Evaluate the following cells**

In [205]:
import numpy as np
np.__version__

'2.0.2'

In [206]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [207]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [208]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'

np.linspace?

## **Creating Vectors and Matrices**

### Creating vectors

In [209]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [210]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [211]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [212]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 0.4132328 ,  0.9035795 ,  1.0721428 ],
        [ 0.68615832,  1.12342402,  0.62718921],
        [ 0.89723983,  0.41757227, -1.28450201]]),
 array([[0.87616629, 0.0414162 , 0.23212158],
        [0.84343786, 0.12337842, 0.82931882],
        [0.47824294, 0.88619386, 0.37326136]]))

In [213]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)
print("Random Matrix:")
print(random_matrix)

# Calculate the symmetric part
symmetric_part = 0.5 * (random_matrix + random_matrix.T)
print("\nSymmetric Part:")
print(symmetric_part)

# Calculate the antisymmetric part
antisymmetric_part = 0.5 * (random_matrix - random_matrix.T)
print("\nAntisymmetric Part:")
print(antisymmetric_part)

# The original matrix should be equal to the sum of its symmetric and antisymmetric parts
verified_matrix = symmetric_part + antisymmetric_part
print("\nVerified Matrix (Symmetric + Antisymmetric):")
print(verified_matrix)

# Check if the decomposition is accurate by comparing with the original matrix
print("\nIs original_matrix approximately equal to (symmetric_part + antisymmetric_part)?")
if np.allclose(random_matrix, verified_matrix):
    print("Yes, the decomposition is accurate.")
else:
    print("No, the decomposition is not accurate.")

Random Matrix:
[[0.37227982 0.19370548 0.87331362 0.60639092 0.07378938]
 [0.21296068 0.16109095 0.28642088 0.5931626  0.88257167]
 [0.09442224 0.11556094 0.84574    0.87663239 0.63038804]
 [0.29530284 0.42357261 0.71702127 0.99441806 0.15534978]
 [0.65089674 0.96521004 0.01319829 0.87230349 0.60950477]]

Symmetric Part:
[[0.37227982 0.20333308 0.48386793 0.45084688 0.36234306]
 [0.20333308 0.16109095 0.20099091 0.50836761 0.92389086]
 [0.48386793 0.20099091 0.84574    0.79682683 0.32179316]
 [0.45084688 0.50836761 0.79682683 0.99441806 0.51382664]
 [0.36234306 0.92389086 0.32179316 0.51382664 0.60950477]]

Antisymmetric Part:
[[ 0.         -0.0096276   0.38944569  0.15554404 -0.28855368]
 [ 0.0096276   0.          0.08542997  0.08479499 -0.04131918]
 [-0.38944569 -0.08542997  0.          0.07980556  0.30859487]
 [-0.15554404 -0.08479499 -0.07980556  0.         -0.35847686]
 [ 0.28855368  0.04131918 -0.30859487  0.35847686  0.        ]]

Verified Matrix (Symmetric + Antisymmetric):
[[0

# Operations: `*`, `@`, and `np.matmul` / `np.dot`

Elementwise and matrix multiplication are treated differently in Numpy

## Elementwise multiplication (*)

In [214]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

## Matrix multiplication (@)

In [215]:
A @ B

array([[ 70, 100],
       [150, 220]])

## Function equivalents for matrix multiplication

In [216]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [217]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences


# Explanations:

# np.matmul:
# Standard matrix multiplication function
# For 2D matrices, the number of columns of the first matrix must be the same as the numnber of rows in the second matrix
# For any matrices with more than two dimensions, they are treated like stacks of matrices
# np.matmul does not work with scalars; you cannot use np.matmul to scale a matrix by a value

# np.dot:
# Standard dot product function
# For 1D arrays (vectors), the dot product is computed as expected (a1b1 + a2b2 + ...)
# For 0D arrays (scalars), the product is found (element-wise multiplication)
# For 2D arrays (matrices), matrix multiplication is carried out (similar to np.matmul and @)
# For ND arrays dotted with 1D arrays, the result is a sum product over the last axis of the first array
# For ND arrays dotted with MD arrays (where M is greater than or equal to 2), the result is a sum product over the last axis of the first array and the penultimate axis of the second array

# @:
# Standard matrix multiplication function
# This works exactly the same as `np.matmul`

# *:
# Standard element-wise multiplication function
# Allows for multiplication of scalars (0D arrays); result is an array scaled by that value
# If the shapes of the arrays are identical, the result is a new array with corresponding elements being multiplied by each other
# If the shapes of the arrays are not identical, the result is a new array with dimensions that NumPy dictates as common; same corresponding element multiplication

## Examples:

In [218]:
# Arrays to be used
A = np.array([[1,2],[3,4]]) # 2x2 matrix
B = np.array([[10,20],[30,40]]) # 2x2 matrix
C = 5 # 0D scalar
D = np.array([[5],[6]]) # 2x1 vector

### `np.matmul` examples

In [219]:
np.matmul(A, B) # Result is a 2x2 matrix with matrix multiplication of A and B

array([[ 70, 100],
       [150, 220]])

In [220]:
# np.matmul(A, C) # Result is an error message, since `np.matmul` does not work with scalars

### `np.dot` examples

In [221]:
np.dot(A, B) # Result is a 2x1 array with components being a1b1 + a2b2, etc.

array([[ 70, 100],
       [150, 220]])

In [222]:
np.dot(C, C) # Result is element-wise multiplication

np.int64(25)

In [223]:
np.dot(A, B) # Result is matrix multiplication; same as `np.matmul(A, B)`

array([[ 70, 100],
       [150, 220]])

### `@` examples

In [224]:
A @ B # Result is matrix multiplication; same as `np.matmul(A, B)`

array([[ 70, 100],
       [150, 220]])

In [225]:
# A @ C # Result is an error message, since `@` does not work with scalars

### `*` examples

In [226]:
A * B # Result is a 2x2 matrix with components being products of corresponding components in A and B

array([[ 10,  40],
       [ 90, 160]])

In [227]:
A * D # Result is a 2x2 matrix with components being products of corresponding rows (since D is 2x1)

array([[ 5, 10],
       [18, 24]])

## Vectorization and Performance

Vectorization means applying operations to whole arrays at once, rather than element by element

### Loop version -- one element at a time

In [228]:
import math

In [229]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

266 ms ± 9.77 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [230]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

19.3 ms ± 3.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [231]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

# Gemini says "The %%timeit is an IPython magic command that is used to measure the execution time of Python code. It runs the code multiple times and provides the average, standard deviation, and best time of the execution. This is very useful for performance profiling and comparing the efficiency of different code implementations."

In [232]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

def total_energy_harmonic_oscillator(m, k, x, v):
    """
    Calculates the total energy (kinetic + potential) of a harmonic oscillator
    in a vectorized manner.

    Parameters:
    m (float or np.ndarray): Mass of the oscillating particle(s).
    k (float or np.ndarray): Spring constant of the oscillator(s).
    x (float or np.ndarray): Position(s) of the particle(s).
    v (float or np.ndarray): Velocity/velocities of the particle(s).

    Returns:
    np.ndarray: Total energy (T + U) for each corresponding x and v.
    """
    kinetic_energy = 0.5 * m * v**2
    potential_energy = 0.5 * k * x**2
    return kinetic_energy + potential_energy

m = 1 # mass in kilograms
k = 1 # spring constant in Newtons per meter

# Define arrays of positions and velocities
positions = np.array([0.1, 0.2, 0.0, -0.1, -0.2])  # meters
velocities = np.array([0.5, 0.0, -0.5, 0.3, 0.1])  # meters per second

# Calculate total energy using the vectorized function
total_energies = total_energy_harmonic_oscillator(m, k, positions, velocities)

print("Positions:", positions)
print("Velocities:", velocities)
print("Total Energies:", total_energies)

m_array = np.array([1.0, 2.0]) # mass vector
k_array = np.array([10.0, 5.0]) # spring constant vector
x_array = np.array([0.1, 0.2]) # position vector
v_array = np.array([0.5, 0.1]) # velocity vector

mixed_energies = total_energy_harmonic_oscillator(m_array, k_array, x_array, v_array)
print("\nMixed (array) parameters energies:", mixed_energies)

Positions: [ 0.1  0.2  0.  -0.1 -0.2]
Velocities: [ 0.5  0.  -0.5  0.3  0.1]
Total Energies: [0.13  0.02  0.125 0.05  0.025]

Mixed (array) parameters energies: [0.175 0.11 ]


## Eigenvalues and Eigenvectors

For a matrix M, eigenvalues $\lambda$ and eigenvectors v satisfy:

$$Mv = \lambda v$$

In physics, these often realte to characteristic and measurable physical quantities:

- Oscillators → $\lambda$ relates to squared frequencies
- Quantum mechanics → $\lambda$ could be the energy eigenstates
- Rotations → $\lambda$ could define a principal axes


### Here is an example matrix

In [233]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [234]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

# The eigenvalues are in order with which eigenvector they represent:
# 9.996...e-17 corresponds to the first column
# 1.000...e+00 corresponds to the second column
# 3.000...e-01 corresponds to the third column

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule ($O_2$ or $N_2$, for example) as two masses connected by a spring. Motion is restricted to the bond axis.

The (quadratic) potential energy is: $V = 0.5 * x.T @ K @ x$  where $x = (x1, x2)$, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [235]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [236]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [237]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors U forms a unitary transformation.

In [238]:
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.


# Eigenvectors of a symmetric matrix are orthonormal, forming a unitary matrix.
M_symmetric = np.array([[2, 1], [1, 2]])

# Find eigenvalues and eigenvectors
# np.linalg.eigh returns eigenvectors that form a unitary matrix
vals_M, U_eigenvectors = np.linalg.eigh(M_symmetric)

print("Original Symmetric Matrix M:")
print(M_symmetric)
print("\nEigenvectors (U_eigenvectors):")
print(U_eigenvectors)

# Show that U@U.T is an identity matrix
product1 = U_eigenvectors @ U_eigenvectors.T
print("\nU_eigenvectors @ U_eigenvectors.T:")
print(product1)

# Show that U.T@U is an identity matrix
product2 = U_eigenvectors.T @ U_eigenvectors
print("\nU_eigenvectors.T @ U_eigenvectors:")
print(product2)

# Both are approximately equal to the 2x2 identity matrix

Original Symmetric Matrix M:
[[2 1]
 [1 2]]

Eigenvectors (U_eigenvectors):
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

U_eigenvectors @ U_eigenvectors.T:
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]

U_eigenvectors.T @ U_eigenvectors:
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]


In [239]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.


# Construct a diagonal matrix (lambda) from the eigenvalues
# vals_M contains the eigenvalues from np.linalg.eigh(M_symmetric)
lambda_matrix = np.diag(vals_M)

print("Original Symmetric Matrix M (K in formula):\n", M_symmetric)
print("\nEigenvector Matrix U:\n", U_eigenvectors)
print("\nDiagonal Eigenvalue Matrix lambda:\n", lambda_matrix)

# Calculate U.T @ K @ U
calculated_lambda = U_eigenvectors.T @ M_symmetric @ U_eigenvectors

print("\nCalculated U.T @ K @ U:\n", calculated_lambda)

# Confirm the behavior by comparing the calculated_lambda with the original lambda_matrix
print("\nIs U.T @ K @ U approximately equal to the diagonal eigenvalue matrix lambda?")
print(np.allclose(calculated_lambda, lambda_matrix))

Original Symmetric Matrix M (K in formula):
 [[2 1]
 [1 2]]

Eigenvector Matrix U:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

Diagonal Eigenvalue Matrix lambda:
 [[1. 0.]
 [0. 3.]]

Calculated U.T @ K @ U:
 [[ 1.00000000e+00  2.23711432e-17]
 [-4.39088730e-17  3.00000000e+00]]

Is U.T @ K @ U approximately equal to the diagonal eigenvalue matrix lambda?
True


In [240]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule


# We diagonalized the stiffness matrix `K` to get the eigenvalues (`vals`) and eigenvectors (`vecs`)
# The first eigenvalue is 0, which means that there is no restoring force for this type of motion in this context
# The corresponding eigenvector is [0.707, 0.707], which means that both atoms move in the same direction with the same magnitude
# The second eigenvalue is 4900, which means that there is in fact a restoring force for vibration
# The corresponding eigenvector is [-0.707, 0.707], which means that both atoms move in opposite directions but with the same magnitude